[SCD-30]
name = "SCD-30"
description = "NDIR CO2, Temperature, and Humidity Sensor"
module = "simoc_sam.sensors.scd30"
i2c_address = 0x61

    [SCD-30.data.CO2]
    unit = "ppm"
    label = "CO2"
    description = "CO2 Concentration"

    [SCD-30.data.temperature]
    unit = "°C"
    label = "Temperature"
    description = "Temperature"

    [SCD-30.data.humidity]
    unit = "%"
    label = "Humidity"
    description = "Relative Humidity"

[SCD-41]
name = "SCD-41"
description = "True CO2 Temperature and Humidity Sensor"
module = "simoc_sam.sensors.scd4x"
i2c_address = 0x62

    [SCD-41.data.CO2]
    unit = "ppm"
    label = "CO2 Concentration"
    description = "CO2 Concentration"

    [SCD-41.data.temperature]
    unit = "°C"
    label = "Temperature"
    description = "Temperature"

    [SCD-41.data.humidity]
    unit = "%"
    label = "Humidity"
    description = "Relative Humidity"

[SGP30]
name = "SGP30"
description = "TVOC/eCO2 Gas Sensor"
module = "simoc_sam.sensors.sgp30"
i2c_address = 0x58

    [SGP30.data.eCO2]
    unit = "ppm"
    label = "eCO2"
    description = "CO2 Equivalent Concentration"

    [SGP30.data.TVOC]
    unit = "ppb"
    label = "TVOC"
    description = "Total Volatile Organic Compounds"

    [SGP30.data.H2]
    unit = "ppm"
    label = "Hydrogen"
    description =  "Hydrogen Concentration"

    [SGP30.data.ethanol]
    unit = "ppm"
    label = "Ethanol"
    description = "Ethanol Concentration"

[BME688]
name = "BME688"
description = "Temperature, Humidity, Pressure, and Gas Sensor"
module = "simoc_sam.sensors.bme688"
i2c_address = 0x77

    [BME688.data.temperature]
    unit = "°C"
    label = "Temperature"
    description = "Temperature"

    [BME688.data.pressure]
    unit = "hPa"
    label = "Pressure"
    description = "Barometric Pressure"

    [BME688.data.humidity]
    unit = "%"
    label = "Humidity"
    description = "Relative Humidity"

    [BME688.data.gas_resistance]
    unit = "Ohm"
    label = "Gas"
    description = "Gas Resistance (based on VOC)"

    [BME688.data.altitude]
    unit = "m"
    label = "Altitude"
    description = "Altitude"

[APDS9960]
name = "APDS9960"
description = "Proximity, Light, RGB, and Gesture Sensor"
module = ""
i2c_address = 0x39

    [APDS9960.data.proximity]
    unit = ""
    label = "Proximity"
    description = "Proximity"

    [APDS9960.data.gesture]
    unit = ""
    label = "Gesture"
    description = "Gesture"

    [APDS9960.data.color]
    unit = ""
    label = "Color"
    description = "Color"

[TSL2591]
name = "TSL2591"
description = "High Dynamic Range Digital Light Sensor"
module = ""
i2c_address = 0x29

    [TSL2591.data.light]
    unit = "lux"
    label = "Light"
    description = "Light Intensity"

    [TSL2591.data.visible]
    unit = ""
    label = "Visible"
    description = "Visible Light Level"

    [TSL2591.data.infrared]
    unit = ""
    label = "Infrared"
    description = "Infrared Light Level"

[VEML7700]
name = "VEML7700"
description = "Ambient Light Sensor"
module = ""
i2c_address = 0x10

    [VEML7700.data.light]
    unit = "Lux"
    label = "Light"
    description = "Ambient Light"
